//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launch_KoLMafia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launch_KoLMafia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jar file found in the provided folder. Download latest mafia to {0}?.
        /// </summary>
        internal static string DownloadToNewConfirmMsg {
            get {
                return ResourceManager.GetString("DownloadToNewConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia Not Found!.
        /// </summary>
        internal static string DownloadToNewConfirmTitle {
            get {
                return ResourceManager.GetString("DownloadToNewConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITS exception {0:X} {1}.
        /// </summary>
        internal static string ErrorBitsException {
            get {
                return ResourceManager.GetString("ErrorBitsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where you want to install KoLMafia.
        /// </summary>
        internal static string FolderSelectTitle {
            get {
                return ResourceManager.GetString("FolderSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location of KolMafia JAR.
        /// </summary>
        internal static string JarFileSelectTitle {
            get {
                return ResourceManager.GetString("JarFileSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An updated version({0}) of KoLMafia Launcher is available! Update now? (Or skip this release ?).
        /// </summary>
        internal static string NewVersionDialogMsg {
            get {
                return ResourceManager.GetString("NewVersionDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An updated version({0}) of KoLMafia Launcher is available! Update now?.
        /// </summary>
        internal static string NewVersionDialogMsgNoSkip {
            get {
                return ResourceManager.GetString("NewVersionDialogMsgNoSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        internal static string NewVersionDialogTitle {
            get {
                return ResourceManager.GetString("NewVersionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} process has been detected. For safety, update cannot continue without killing this process..
        /// </summary>
        internal static string ProcessConflictDialogMsg {
            get {
                return ResourceManager.GetString("ProcessConflictDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Interpreter Already Running.
        /// </summary>
        internal static string ProcessConflictDialogTitle {
            get {
                return ResourceManager.GetString("ProcessConflictDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a error when attempting to retreive and/or save the latest version. Your previous version has been kept, and will now be run..
        /// </summary>
        internal static string RetreivalError {
            get {
                return ResourceManager.GetString("RetreivalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreival error!.
        /// </summary>
        internal static string RetreivalErrorTitle {
            get {
                return ResourceManager.GetString("RetreivalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registry config found, silence precludes requesting install location..
        /// </summary>
        internal static string SilentEmptyRegistryError {
            get {
                return ResourceManager.GetString("SilentEmptyRegistryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was selected. Should Launcher assume you don&apos;t have KoLMafia installed and ask where you want it? (Selecting No will exit immediately).
        /// </summary>
        internal static string TargetFolderDialogMsg {
            get {
                return ResourceManager.GetString("TargetFolderDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string TargetFolderDialogTitle {
            get {
                return ResourceManager.GetString("TargetFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have authorization to access that file.
        /// </summary>
        internal static string UnauthorizedAccessMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access.
        /// </summary>
        internal static string UnauthorizedAccessTitle {
            get {
                return ResourceManager.GetString("UnauthorizedAccessTitle", resourceCulture);
            }
        }
    }
}
